project_id = "wwolnohfqmihuokqqhpw"

[functions.lookup-patient-by-id]
verify_jwt = false

[functions.connect-to-doctor]
verify_jwt = false

[functions.generate-doctor-document-url]
verify_jwt = false
